# Jujutsu (jj) — Git-compatible VCS. Completions are dynamic (clap), generated by the
# binary itself, so they stay in sync with whatever version is installed.

if (( $+commands[jj] )); then
  source <(COMPLETE=zsh jj 2>/dev/null)

  alias jjs='jj status'
  alias jjl='jj log'
  alias jjd='jj diff'
fi
