#!/bin/bash
#### git ####

function pull {
    git remote prune origin
    git pull
}

function branch {
    git checkout -b $1
    git push --set-upstream origin $1
}

function delbranch {
    git push origin --delete $1
    git branch -D $1
}
