#!/usr/bin/env bash


# $PATH - load path from ~/.path
if [[ -e "$HOME/.path" ]]; then
    path=""
    while read -r; do
        eval "item=\"$REPLY\""
        if [[ ! -z "$path" ]]; then path="$path:"; fi
        path="$path$item"
    done < "$HOME/.path"
    export PATH="$path"
fi

# $MANPATH - load manpath from ~/.manpath
if [[ -e "$HOME/.manpath" ]]; then
    manpath=""
    while read -r; do
        eval "item=\"$REPLY\""
        if [[ ! -z "$manpath" ]]; then manpath="$manpath:"; fi
        manpath="$manpath$item"
    done < "$HOME/.manpath"
    export MANPATH="$manpath"
fi



# local flavours
for f in ~/.bash.d/*; do
    source $f;
done

if [[ -e ~/.localrc ]]
then
  source ~/.localrc
fi
. "$HOME/.cargo/env"
